# Theme
remote_theme: mistic100/jekyll-bootstrap-doc

# Project Name
name: CalcKit

# Header
header:
  color1: "#080331"
  color2: "#673051"
  trianglify: true

# List of additional links on the right of the top menu
headerLinks:
  - title: Open CalcKit
    url: https://app.calckit.io
