# Theme
remote_theme: allejo/jekyll-docs-theme

name: CalcKit Docs

# Set this to true to replace the generated header navbar by _includes/navbar.html
#customNavBar: true

# Header
ui:
    header:
        #color1: "#0074d9"
        #color2: "#001f3f"
        color1: "#0066bf"
        color2: "#002f5d"
        trianglify: true

# List of additional links on the right of the top menu
links:
    header:
      - title: Open CalcKit
        url: https://app.calckit.io
