# Theme
remote_theme: allejo/jekyll-docs-theme

# Project Name
name: CalcKit

# Set this to true to replace the generated header navbar by _includes/navbar.html
customNavBar: false

# Header
ui:
    header:
        color1: "#000000"
        color2: "#673051"
        trianglify: true

# List of additional links on the right of the top menu
links:
    header:
      - title: Open CalcKit
        url: https://app.calckit.io

project:
    version: 0.1.0
    download_url: https://github.com/allejo/jekyll-docs-theme/releases
