# Theme
remote_theme: allejo/jekyll-docs-theme

# Set this to true to replace the generated header navbar by _includes/navbar.html
customNavBar: ture

# Header
ui:
    header:
        color1: "#424242"
        color2: "#14a7c9"
        trianglify: true

# List of additional links on the right of the top menu
links:
    header:
      - title: Open CalcKit
        url: https://app.calckit.io
