# Theme
remote_theme: allejo/jekyll-docs-theme

# Project Name
name: CalcKit

# Set this to true to replace the generated header navbar by _includes/navbar.html
customNavBar: false

# Header
header:
  color1: "#080331"
  color2: "#673051"
  trianglify: true

# List of additional links on the right of the top menu
headerLinks:
  - title: Open CalcKit
    url: https://app.calckit.io
